version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx.Dockerfile
    volumes:
      - "./certs:/etc/nginx/certs"
    environment:
      NGINX_SSL_CERTIFICATE: /etc/nginx/certs/ackerleytng.com.pem
      NGINX_SSL_CERTIFICATE_KEY: /etc/nginx/certs/ackerleytng.com.key
      NGINX_SSL_CLIENT_CERTIFICATE: /etc/nginx/certs/cloudflare.crt
      NGINX_SERVER_NAME: gowherene.ackerleytng.com
      BACKEND_PORT: ${BACKEND_PORT:-3000}
    ports:
      - "443:443"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/gowherene.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  backend:
    build:
      context: .
      dockerfile: ./compose/backend.Dockerfile
    environment:
      GOOGLE_API_TOKEN: ${GOOGLE_API_TOKEN:?Please provide GOOGLE_API_TOKEN as an environment variable}
      PORT: ${BACKEND_PORT:-3000}
